/// <summary>
///*****************************************************************************
/// Copyright (c) 2009, 2018 IBM Corporation and others.
/// This program and the accompanying materials
/// are made available under the terms of the Eclipse Public License 2.0
/// which accompanies this distribution, and is available at
/// https://www.eclipse.org/legal/epl-2.0/
/// 
/// SPDX-License-Identifier: EPL-2.0
/// 
/// Contributors:
///     IBM Corporation - initial API and implementation
/// ******************************************************************************
/// </summary>

//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Apr 04 11:19:53 CEST 2013
//----------------------------------------------------

namespace org.eclipse.wst.xml.xpath2.processor.@internal
{

	/// <summary>
	/// CUP generated class containing symbol constants. </summary>
	public class XpathSym
	{
	  /* terminals */
	  public const int DESCENDANT_OR_SELF = 32;
	  public const int AS = 56;
	  public const int GT = 45;
	  public const int FOLLOWING = 34;
	  public const int FORWARD_SLASHSLASH = 19;
	  public const int PARENT = 36;
	  public const int GE = 46;
	  public const int DOCUMENT_NODE = 75;
	  public const int NAMESPACE = 35;
	  public const int FORWARD_SLASH = 18;
	  public const int TREAT = 55;
	  public const int NODE = 74;
	  public const int COMMA = 24;
	  public const int ANCESTOR = 37;
	  public const int LT = 43;
	  public const int INTEGER = 83;
	  public const int DOUBLE = 84;
	  public const int CHILD = 28;
	  public const int FOLLOWING_SIBLING = 33;
	  public const int EVERY = 66;
	  public const int SELF = 31;
	  public const int LE = 44;
	  public const int ELEMENT = 80;
	  public const int TEXT = 76;
	  public const int INSTANCE = 53;
	  public const int NOTEQUALS = 11;
	  public const int THEN = 68;
	  public const int SCHEMA_ELEMENT = 81;
	  public const int SCHEMA_ATTRIBUTE = 79;
	  public const int ANCESTOR_OR_SELF = 40;
	  public const int EQ = 41;
	  public const int PRECEDING = 39;
	  public const int MOD = 49;
	  public const int AT_SYM = 21;
	  public const int DOLLAR = 25;
	  public const int EXCEPT = 52;
	  public const int LESSTHAN = 12;
	  public const int PIPE = 9;
	  public const int LESSEQUAL = 13;
	  public const int QUESTIONMARK = 27;
	  public const int PLUS = 6;
	  public const int IDIV = 48;
	  public const int LPAR = 4;
	  public const int UNION = 50;
	  public const int GREATEREQUAL = 15;
	  public const int DECIMAL = 85;
	  public const int FOR = 60;
	  public const int STAR = 8;
	  public const int GREATER = 14;
	  public const int PRECEDING_SIBLING = 38;
	  public const int DIV = 47;
	  public const int RETURN = 62;
	  public const int ELSE = 69;
	  public const int DOTDOT = 22;
	  public const int DOT = 26;
	  public const int EOF = 0;
	  public const int NCNAME = 87;
	  public const int COMMENT = 77;
	  public const int INTERSECT = 51;
	  public const int RPAR = 5;
	  public const int ITEM = 73;
	  public const int EMPTY_SEQUENCE = 72;
	  public const int CASTABLE = 57;
	  public const int IS = 59;
	  public const int MINUS = 7;
	  public const int PROCESSING_INSTRUCTION = 78;
	  public const int IN = 61;
	  public const int OR = 71;
	  public const int error = 1;
	  public const int ATTRIBUTE = 30;
	  public const int IF = 67;
	  public const int TYPESWITCH = 82;
	  public const int CAST = 58;
	  public const int OF = 54;
	  public const int COLON = 23;
	  public const int DESCENDANT = 29;
	  public const int SOME = 65;
	  public const int RBRACKET = 3;
	  public const int COLONCOLON = 20;
	  public const int GREATER_GREATER = 17;
	  public const int STRING = 86;
	  public const int SATISFIES = 63;
	  public const int AND = 70;
	  public const int TO = 64;
	  public const int LBRACKET = 2;
	  public const int NE = 42;
	  public const int LESS_LESS = 16;
	  public const int EQUALS = 10;
	}


}