//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Quorum.g4 by ANTLR 4.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="QuorumParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6")]
[System.CLSCompliant(false)]
public interface IQuorumVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="QuorumParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStart([NotNull] QuorumParser.StartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QuorumParser.package_rule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackage_rule([NotNull] QuorumParser.Package_ruleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QuorumParser.reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReference([NotNull] QuorumParser.ReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FullClassDeclaration</c>
	/// labeled alternative in <see cref="QuorumParser.class_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFullClassDeclaration([NotNull] QuorumParser.FullClassDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NoClassDeclaration</c>
	/// labeled alternative in <see cref="QuorumParser.class_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoClassDeclaration([NotNull] QuorumParser.NoClassDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NoActionsNoClass</c>
	/// labeled alternative in <see cref="QuorumParser.no_class_stmnts"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoActionsNoClass([NotNull] QuorumParser.NoActionsNoClassContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ActionsNoClass</c>
	/// labeled alternative in <see cref="QuorumParser.no_class_stmnts"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActionsNoClass([NotNull] QuorumParser.ActionsNoClassContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QuorumParser.inherit_stmnts"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInherit_stmnts([NotNull] QuorumParser.Inherit_stmntsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QuorumParser.inherit_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInherit_stmt([NotNull] QuorumParser.Inherit_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QuorumParser.access_modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccess_modifier([NotNull] QuorumParser.Access_modifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QuorumParser.class_stmnts"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_stmnts([NotNull] QuorumParser.Class_stmntsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Action</c>
	/// labeled alternative in <see cref="QuorumParser.method_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAction([NotNull] QuorumParser.ActionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BlueprintAction</c>
	/// labeled alternative in <see cref="QuorumParser.method_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlueprintAction([NotNull] QuorumParser.BlueprintActionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NativeAction</c>
	/// labeled alternative in <see cref="QuorumParser.method_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNativeAction([NotNull] QuorumParser.NativeActionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Constructor</c>
	/// labeled alternative in <see cref="QuorumParser.method_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstructor([NotNull] QuorumParser.ConstructorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QuorumParser.method_shared"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_shared([NotNull] QuorumParser.Method_sharedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QuorumParser.formal_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormal_parameter([NotNull] QuorumParser.Formal_parameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QuorumParser.qualified_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualified_name([NotNull] QuorumParser.Qualified_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QuorumParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] QuorumParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QuorumParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] QuorumParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>VariableSoloFunctionCall</c>
	/// labeled alternative in <see cref="QuorumParser.solo_method_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableSoloFunctionCall([NotNull] QuorumParser.VariableSoloFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ParentVariableSoloFunctionCall</c>
	/// labeled alternative in <see cref="QuorumParser.solo_method_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParentVariableSoloFunctionCall([NotNull] QuorumParser.ParentVariableSoloFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QuorumParser.solo_method_required_method_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSolo_method_required_method_part([NotNull] QuorumParser.Solo_method_required_method_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QuorumParser.alert_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlert_statement([NotNull] QuorumParser.Alert_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QuorumParser.check_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCheck_statement([NotNull] QuorumParser.Check_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QuorumParser.detect_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDetect_statement([NotNull] QuorumParser.Detect_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QuorumParser.always_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlways_statement([NotNull] QuorumParser.Always_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QuorumParser.print_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrint_statement([NotNull] QuorumParser.Print_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QuorumParser.speak_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpeak_statement([NotNull] QuorumParser.Speak_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QuorumParser.return_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn_statement([NotNull] QuorumParser.Return_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QuorumParser.generic_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneric_declaration([NotNull] QuorumParser.Generic_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QuorumParser.generic_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneric_statement([NotNull] QuorumParser.Generic_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QuorumParser.class_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_type([NotNull] QuorumParser.Class_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GenericAssignmentDeclaration</c>
	/// labeled alternative in <see cref="QuorumParser.assignment_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenericAssignmentDeclaration([NotNull] QuorumParser.GenericAssignmentDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IntegerAssignmentDeclaration</c>
	/// labeled alternative in <see cref="QuorumParser.assignment_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntegerAssignmentDeclaration([NotNull] QuorumParser.IntegerAssignmentDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NumberAssignmentDeclaration</c>
	/// labeled alternative in <see cref="QuorumParser.assignment_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberAssignmentDeclaration([NotNull] QuorumParser.NumberAssignmentDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TextAssignmentDeclaration</c>
	/// labeled alternative in <see cref="QuorumParser.assignment_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTextAssignmentDeclaration([NotNull] QuorumParser.TextAssignmentDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BooleanAssignmentDeclaration</c>
	/// labeled alternative in <see cref="QuorumParser.assignment_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanAssignmentDeclaration([NotNull] QuorumParser.BooleanAssignmentDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NoTypeAssignment</c>
	/// labeled alternative in <see cref="QuorumParser.assignment_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoTypeAssignment([NotNull] QuorumParser.NoTypeAssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ParentAssignment</c>
	/// labeled alternative in <see cref="QuorumParser.assignment_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParentAssignment([NotNull] QuorumParser.ParentAssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ObjectAssignment</c>
	/// labeled alternative in <see cref="QuorumParser.assignment_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectAssignment([NotNull] QuorumParser.ObjectAssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NormalAssignment</c>
	/// labeled alternative in <see cref="QuorumParser.assignment_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNormalAssignment([NotNull] QuorumParser.NormalAssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QuorumParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_statement([NotNull] QuorumParser.If_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QuorumParser.elseif_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseif_statement([NotNull] QuorumParser.Elseif_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QuorumParser.else_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElse_statement([NotNull] QuorumParser.Else_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QuorumParser.loop_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoop_statement([NotNull] QuorumParser.Loop_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QuorumParser.initial_parent_action_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitial_parent_action_call([NotNull] QuorumParser.Initial_parent_action_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QuorumParser.action_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAction_call([NotNull] QuorumParser.Action_callContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Cast</c>
	/// labeled alternative in <see cref="QuorumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCast([NotNull] QuorumParser.CastContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Null</c>
	/// labeled alternative in <see cref="QuorumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNull([NotNull] QuorumParser.NullContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Multiplication</c>
	/// labeled alternative in <see cref="QuorumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplication([NotNull] QuorumParser.MultiplicationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Addition</c>
	/// labeled alternative in <see cref="QuorumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddition([NotNull] QuorumParser.AdditionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Or</c>
	/// labeled alternative in <see cref="QuorumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOr([NotNull] QuorumParser.OrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ParenthesisExpression</c>
	/// labeled alternative in <see cref="QuorumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesisExpression([NotNull] QuorumParser.ParenthesisExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Inherits</c>
	/// labeled alternative in <see cref="QuorumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInherits([NotNull] QuorumParser.InheritsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>String</c>
	/// labeled alternative in <see cref="QuorumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] QuorumParser.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Integer</c>
	/// labeled alternative in <see cref="QuorumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInteger([NotNull] QuorumParser.IntegerContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>VariableFunctionCall</c>
	/// labeled alternative in <see cref="QuorumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableFunctionCall([NotNull] QuorumParser.VariableFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Input</c>
	/// labeled alternative in <see cref="QuorumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInput([NotNull] QuorumParser.InputContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Not</c>
	/// labeled alternative in <see cref="QuorumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNot([NotNull] QuorumParser.NotContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Equals</c>
	/// labeled alternative in <see cref="QuorumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquals([NotNull] QuorumParser.EqualsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Decimal</c>
	/// labeled alternative in <see cref="QuorumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecimal([NotNull] QuorumParser.DecimalContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>And</c>
	/// labeled alternative in <see cref="QuorumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnd([NotNull] QuorumParser.AndContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Me</c>
	/// labeled alternative in <see cref="QuorumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMe([NotNull] QuorumParser.MeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Greater</c>
	/// labeled alternative in <see cref="QuorumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGreater([NotNull] QuorumParser.GreaterContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Boolean</c>
	/// labeled alternative in <see cref="QuorumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolean([NotNull] QuorumParser.BooleanContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>InputNoParameters</c>
	/// labeled alternative in <see cref="QuorumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInputNoParameters([NotNull] QuorumParser.InputNoParametersContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ParentVariableFunctionCall</c>
	/// labeled alternative in <see cref="QuorumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParentVariableFunctionCall([NotNull] QuorumParser.ParentVariableFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Minus</c>
	/// labeled alternative in <see cref="QuorumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMinus([NotNull] QuorumParser.MinusContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QuorumParser.function_expression_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_expression_list([NotNull] QuorumParser.Function_expression_listContext context);
}
