//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from tsql.g4 by ANTLR 4.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="tsqlParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6")]
[System.CLSCompliant(false)]
public interface ItsqlListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.tsql_file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTsql_file([NotNull] tsqlParser.Tsql_fileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.tsql_file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTsql_file([NotNull] tsqlParser.Tsql_fileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.sql_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSql_clause([NotNull] tsqlParser.Sql_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.sql_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSql_clause([NotNull] tsqlParser.Sql_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.dml_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDml_clause([NotNull] tsqlParser.Dml_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.dml_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDml_clause([NotNull] tsqlParser.Dml_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.ddl_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDdl_clause([NotNull] tsqlParser.Ddl_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.ddl_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDdl_clause([NotNull] tsqlParser.Ddl_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>begin_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBegin_statement([NotNull] tsqlParser.Begin_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>begin_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBegin_statement([NotNull] tsqlParser.Begin_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>break_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBreak_statement([NotNull] tsqlParser.Break_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>break_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBreak_statement([NotNull] tsqlParser.Break_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>continue_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContinue_statement([NotNull] tsqlParser.Continue_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>continue_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContinue_statement([NotNull] tsqlParser.Continue_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>goto_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGoto_statement([NotNull] tsqlParser.Goto_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>goto_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGoto_statement([NotNull] tsqlParser.Goto_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>if_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf_statement([NotNull] tsqlParser.If_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>if_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf_statement([NotNull] tsqlParser.If_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>return_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturn_statement([NotNull] tsqlParser.Return_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>return_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturn_statement([NotNull] tsqlParser.Return_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>throw_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThrow_statement([NotNull] tsqlParser.Throw_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>throw_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThrow_statement([NotNull] tsqlParser.Throw_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>try_catch_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTry_catch_statement([NotNull] tsqlParser.Try_catch_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>try_catch_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTry_catch_statement([NotNull] tsqlParser.Try_catch_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>waitfor_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWaitfor_statement([NotNull] tsqlParser.Waitfor_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>waitfor_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWaitfor_statement([NotNull] tsqlParser.Waitfor_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>while_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhile_statement([NotNull] tsqlParser.While_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>while_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhile_statement([NotNull] tsqlParser.While_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>print_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrint_statement([NotNull] tsqlParser.Print_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>print_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrint_statement([NotNull] tsqlParser.Print_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>raiseerror_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRaiseerror_statement([NotNull] tsqlParser.Raiseerror_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>raiseerror_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRaiseerror_statement([NotNull] tsqlParser.Raiseerror_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.another_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnother_statement([NotNull] tsqlParser.Another_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.another_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnother_statement([NotNull] tsqlParser.Another_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.delete_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDelete_statement([NotNull] tsqlParser.Delete_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.delete_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDelete_statement([NotNull] tsqlParser.Delete_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.insert_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInsert_statement([NotNull] tsqlParser.Insert_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.insert_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInsert_statement([NotNull] tsqlParser.Insert_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.select_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelect_statement([NotNull] tsqlParser.Select_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.select_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelect_statement([NotNull] tsqlParser.Select_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.update_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUpdate_statement([NotNull] tsqlParser.Update_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.update_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUpdate_statement([NotNull] tsqlParser.Update_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.output_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOutput_clause([NotNull] tsqlParser.Output_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.output_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOutput_clause([NotNull] tsqlParser.Output_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.output_dml_list_elem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOutput_dml_list_elem([NotNull] tsqlParser.Output_dml_list_elemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.output_dml_list_elem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOutput_dml_list_elem([NotNull] tsqlParser.Output_dml_list_elemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.output_column_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOutput_column_name([NotNull] tsqlParser.Output_column_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.output_column_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOutput_column_name([NotNull] tsqlParser.Output_column_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.create_index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreate_index([NotNull] tsqlParser.Create_indexContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.create_index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreate_index([NotNull] tsqlParser.Create_indexContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.create_procedure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreate_procedure([NotNull] tsqlParser.Create_procedureContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.create_procedure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreate_procedure([NotNull] tsqlParser.Create_procedureContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.procedure_param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedure_param([NotNull] tsqlParser.Procedure_paramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.procedure_param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedure_param([NotNull] tsqlParser.Procedure_paramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.procedure_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedure_option([NotNull] tsqlParser.Procedure_optionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.procedure_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedure_option([NotNull] tsqlParser.Procedure_optionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.create_statistics"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreate_statistics([NotNull] tsqlParser.Create_statisticsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.create_statistics"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreate_statistics([NotNull] tsqlParser.Create_statisticsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.create_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreate_table([NotNull] tsqlParser.Create_tableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.create_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreate_table([NotNull] tsqlParser.Create_tableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.create_view"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreate_view([NotNull] tsqlParser.Create_viewContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.create_view"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreate_view([NotNull] tsqlParser.Create_viewContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.view_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterView_attribute([NotNull] tsqlParser.View_attributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.view_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitView_attribute([NotNull] tsqlParser.View_attributeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.alter_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlter_table([NotNull] tsqlParser.Alter_tableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.alter_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlter_table([NotNull] tsqlParser.Alter_tableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.alter_database"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlter_database([NotNull] tsqlParser.Alter_databaseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.alter_database"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlter_database([NotNull] tsqlParser.Alter_databaseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.database_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDatabase_option([NotNull] tsqlParser.Database_optionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.database_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDatabase_option([NotNull] tsqlParser.Database_optionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.drop_index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDrop_index([NotNull] tsqlParser.Drop_indexContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.drop_index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDrop_index([NotNull] tsqlParser.Drop_indexContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.drop_procedure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDrop_procedure([NotNull] tsqlParser.Drop_procedureContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.drop_procedure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDrop_procedure([NotNull] tsqlParser.Drop_procedureContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.drop_statistics"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDrop_statistics([NotNull] tsqlParser.Drop_statisticsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.drop_statistics"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDrop_statistics([NotNull] tsqlParser.Drop_statisticsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.drop_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDrop_table([NotNull] tsqlParser.Drop_tableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.drop_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDrop_table([NotNull] tsqlParser.Drop_tableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.drop_view"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDrop_view([NotNull] tsqlParser.Drop_viewContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.drop_view"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDrop_view([NotNull] tsqlParser.Drop_viewContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.rowset_function_limited"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRowset_function_limited([NotNull] tsqlParser.Rowset_function_limitedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.rowset_function_limited"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRowset_function_limited([NotNull] tsqlParser.Rowset_function_limitedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.openquery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpenquery([NotNull] tsqlParser.OpenqueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.openquery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpenquery([NotNull] tsqlParser.OpenqueryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.opendatasource"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpendatasource([NotNull] tsqlParser.OpendatasourceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.opendatasource"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpendatasource([NotNull] tsqlParser.OpendatasourceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.declare_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclare_statement([NotNull] tsqlParser.Declare_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.declare_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclare_statement([NotNull] tsqlParser.Declare_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.cursor_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCursor_statement([NotNull] tsqlParser.Cursor_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.cursor_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCursor_statement([NotNull] tsqlParser.Cursor_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.execute_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExecute_statement([NotNull] tsqlParser.Execute_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.execute_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExecute_statement([NotNull] tsqlParser.Execute_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.execute_statement_arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExecute_statement_arg([NotNull] tsqlParser.Execute_statement_argContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.execute_statement_arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExecute_statement_arg([NotNull] tsqlParser.Execute_statement_argContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.execute_var_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExecute_var_string([NotNull] tsqlParser.Execute_var_stringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.execute_var_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExecute_var_string([NotNull] tsqlParser.Execute_var_stringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.security_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSecurity_statement([NotNull] tsqlParser.Security_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.security_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSecurity_statement([NotNull] tsqlParser.Security_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.set_statment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSet_statment([NotNull] tsqlParser.Set_statmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.set_statment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSet_statment([NotNull] tsqlParser.Set_statmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.transaction_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTransaction_statement([NotNull] tsqlParser.Transaction_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.transaction_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTransaction_statement([NotNull] tsqlParser.Transaction_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.go_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGo_statement([NotNull] tsqlParser.Go_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.go_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGo_statement([NotNull] tsqlParser.Go_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.use_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUse_statement([NotNull] tsqlParser.Use_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.use_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUse_statement([NotNull] tsqlParser.Use_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.execute_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExecute_clause([NotNull] tsqlParser.Execute_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.execute_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExecute_clause([NotNull] tsqlParser.Execute_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.declare_local"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclare_local([NotNull] tsqlParser.Declare_localContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.declare_local"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclare_local([NotNull] tsqlParser.Declare_localContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.table_type_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTable_type_definition([NotNull] tsqlParser.Table_type_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.table_type_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTable_type_definition([NotNull] tsqlParser.Table_type_definitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.column_def_table_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColumn_def_table_constraint([NotNull] tsqlParser.Column_def_table_constraintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.column_def_table_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColumn_def_table_constraint([NotNull] tsqlParser.Column_def_table_constraintContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.column_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColumn_definition([NotNull] tsqlParser.Column_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.column_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColumn_definition([NotNull] tsqlParser.Column_definitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.column_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColumn_constraint([NotNull] tsqlParser.Column_constraintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.column_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColumn_constraint([NotNull] tsqlParser.Column_constraintContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.table_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTable_constraint([NotNull] tsqlParser.Table_constraintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.table_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTable_constraint([NotNull] tsqlParser.Table_constraintContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.index_options"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndex_options([NotNull] tsqlParser.Index_optionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.index_options"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndex_options([NotNull] tsqlParser.Index_optionsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.index_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndex_option([NotNull] tsqlParser.Index_optionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.index_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndex_option([NotNull] tsqlParser.Index_optionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.declare_cursor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclare_cursor([NotNull] tsqlParser.Declare_cursorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.declare_cursor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclare_cursor([NotNull] tsqlParser.Declare_cursorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.declare_set_cursor_common"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclare_set_cursor_common([NotNull] tsqlParser.Declare_set_cursor_commonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.declare_set_cursor_common"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclare_set_cursor_common([NotNull] tsqlParser.Declare_set_cursor_commonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.fetch_cursor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFetch_cursor([NotNull] tsqlParser.Fetch_cursorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.fetch_cursor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFetch_cursor([NotNull] tsqlParser.Fetch_cursorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.set_special"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSet_special([NotNull] tsqlParser.Set_specialContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.set_special"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSet_special([NotNull] tsqlParser.Set_specialContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>binary_operator_expression</c>
	/// labeled alternative in <see cref="tsqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinary_operator_expression([NotNull] tsqlParser.Binary_operator_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>binary_operator_expression</c>
	/// labeled alternative in <see cref="tsqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinary_operator_expression([NotNull] tsqlParser.Binary_operator_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>primitive_expression</c>
	/// labeled alternative in <see cref="tsqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimitive_expression([NotNull] tsqlParser.Primitive_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>primitive_expression</c>
	/// labeled alternative in <see cref="tsqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimitive_expression([NotNull] tsqlParser.Primitive_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>bracket_expression</c>
	/// labeled alternative in <see cref="tsqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBracket_expression([NotNull] tsqlParser.Bracket_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>bracket_expression</c>
	/// labeled alternative in <see cref="tsqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBracket_expression([NotNull] tsqlParser.Bracket_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>unary_operator_expression</c>
	/// labeled alternative in <see cref="tsqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnary_operator_expression([NotNull] tsqlParser.Unary_operator_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>unary_operator_expression</c>
	/// labeled alternative in <see cref="tsqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnary_operator_expression([NotNull] tsqlParser.Unary_operator_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>function_call_expression</c>
	/// labeled alternative in <see cref="tsqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_call_expression([NotNull] tsqlParser.Function_call_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>function_call_expression</c>
	/// labeled alternative in <see cref="tsqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_call_expression([NotNull] tsqlParser.Function_call_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>case_expression</c>
	/// labeled alternative in <see cref="tsqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCase_expression([NotNull] tsqlParser.Case_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>case_expression</c>
	/// labeled alternative in <see cref="tsqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCase_expression([NotNull] tsqlParser.Case_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>column_ref_expression</c>
	/// labeled alternative in <see cref="tsqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColumn_ref_expression([NotNull] tsqlParser.Column_ref_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>column_ref_expression</c>
	/// labeled alternative in <see cref="tsqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColumn_ref_expression([NotNull] tsqlParser.Column_ref_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>subquery_expression</c>
	/// labeled alternative in <see cref="tsqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubquery_expression([NotNull] tsqlParser.Subquery_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>subquery_expression</c>
	/// labeled alternative in <see cref="tsqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubquery_expression([NotNull] tsqlParser.Subquery_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.constant_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant_expression([NotNull] tsqlParser.Constant_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.constant_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant_expression([NotNull] tsqlParser.Constant_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.subquery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubquery([NotNull] tsqlParser.SubqueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.subquery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubquery([NotNull] tsqlParser.SubqueryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.with_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWith_expression([NotNull] tsqlParser.With_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.with_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWith_expression([NotNull] tsqlParser.With_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.common_table_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommon_table_expression([NotNull] tsqlParser.Common_table_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.common_table_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommon_table_expression([NotNull] tsqlParser.Common_table_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.update_elem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUpdate_elem([NotNull] tsqlParser.Update_elemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.update_elem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUpdate_elem([NotNull] tsqlParser.Update_elemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.search_condition_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSearch_condition_list([NotNull] tsqlParser.Search_condition_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.search_condition_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSearch_condition_list([NotNull] tsqlParser.Search_condition_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.search_condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSearch_condition([NotNull] tsqlParser.Search_conditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.search_condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSearch_condition([NotNull] tsqlParser.Search_conditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.search_condition_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSearch_condition_or([NotNull] tsqlParser.Search_condition_orContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.search_condition_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSearch_condition_or([NotNull] tsqlParser.Search_condition_orContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.search_condition_not"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSearch_condition_not([NotNull] tsqlParser.Search_condition_notContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.search_condition_not"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSearch_condition_not([NotNull] tsqlParser.Search_condition_notContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPredicate([NotNull] tsqlParser.PredicateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPredicate([NotNull] tsqlParser.PredicateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.query_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuery_expression([NotNull] tsqlParser.Query_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.query_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuery_expression([NotNull] tsqlParser.Query_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.union"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnion([NotNull] tsqlParser.UnionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.union"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnion([NotNull] tsqlParser.UnionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.query_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuery_specification([NotNull] tsqlParser.Query_specificationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.query_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuery_specification([NotNull] tsqlParser.Query_specificationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.order_by_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrder_by_clause([NotNull] tsqlParser.Order_by_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.order_by_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrder_by_clause([NotNull] tsqlParser.Order_by_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.for_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFor_clause([NotNull] tsqlParser.For_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.for_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFor_clause([NotNull] tsqlParser.For_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.xml_common_directives"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterXml_common_directives([NotNull] tsqlParser.Xml_common_directivesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.xml_common_directives"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitXml_common_directives([NotNull] tsqlParser.Xml_common_directivesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.order_by_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrder_by_expression([NotNull] tsqlParser.Order_by_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.order_by_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrder_by_expression([NotNull] tsqlParser.Order_by_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.group_by_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroup_by_item([NotNull] tsqlParser.Group_by_itemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.group_by_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroup_by_item([NotNull] tsqlParser.Group_by_itemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.option_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOption_clause([NotNull] tsqlParser.Option_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.option_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOption_clause([NotNull] tsqlParser.Option_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOption([NotNull] tsqlParser.OptionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOption([NotNull] tsqlParser.OptionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.optimize_for_arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptimize_for_arg([NotNull] tsqlParser.Optimize_for_argContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.optimize_for_arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptimize_for_arg([NotNull] tsqlParser.Optimize_for_argContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.select_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelect_list([NotNull] tsqlParser.Select_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.select_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelect_list([NotNull] tsqlParser.Select_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.select_list_elem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelect_list_elem([NotNull] tsqlParser.Select_list_elemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.select_list_elem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelect_list_elem([NotNull] tsqlParser.Select_list_elemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.partition_by_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPartition_by_clause([NotNull] tsqlParser.Partition_by_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.partition_by_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPartition_by_clause([NotNull] tsqlParser.Partition_by_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.table_source"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTable_source([NotNull] tsqlParser.Table_sourceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.table_source"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTable_source([NotNull] tsqlParser.Table_sourceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.table_source_item_joined"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTable_source_item_joined([NotNull] tsqlParser.Table_source_item_joinedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.table_source_item_joined"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTable_source_item_joined([NotNull] tsqlParser.Table_source_item_joinedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.table_source_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTable_source_item([NotNull] tsqlParser.Table_source_itemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.table_source_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTable_source_item([NotNull] tsqlParser.Table_source_itemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.change_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChange_table([NotNull] tsqlParser.Change_tableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.change_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChange_table([NotNull] tsqlParser.Change_tableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.join_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJoin_part([NotNull] tsqlParser.Join_partContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.join_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJoin_part([NotNull] tsqlParser.Join_partContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.table_name_with_hint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTable_name_with_hint([NotNull] tsqlParser.Table_name_with_hintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.table_name_with_hint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTable_name_with_hint([NotNull] tsqlParser.Table_name_with_hintContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.rowset_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRowset_function([NotNull] tsqlParser.Rowset_functionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.rowset_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRowset_function([NotNull] tsqlParser.Rowset_functionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.bulk_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBulk_option([NotNull] tsqlParser.Bulk_optionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.bulk_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBulk_option([NotNull] tsqlParser.Bulk_optionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.derived_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDerived_table([NotNull] tsqlParser.Derived_tableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.derived_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDerived_table([NotNull] tsqlParser.Derived_tableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_call([NotNull] tsqlParser.Function_callContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_call([NotNull] tsqlParser.Function_callContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.datepart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDatepart([NotNull] tsqlParser.DatepartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.datepart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDatepart([NotNull] tsqlParser.DatepartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.as_table_alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAs_table_alias([NotNull] tsqlParser.As_table_aliasContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.as_table_alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAs_table_alias([NotNull] tsqlParser.As_table_aliasContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.table_alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTable_alias([NotNull] tsqlParser.Table_aliasContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.table_alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTable_alias([NotNull] tsqlParser.Table_aliasContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.with_table_hints"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWith_table_hints([NotNull] tsqlParser.With_table_hintsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.with_table_hints"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWith_table_hints([NotNull] tsqlParser.With_table_hintsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.insert_with_table_hints"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInsert_with_table_hints([NotNull] tsqlParser.Insert_with_table_hintsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.insert_with_table_hints"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInsert_with_table_hints([NotNull] tsqlParser.Insert_with_table_hintsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.table_hint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTable_hint([NotNull] tsqlParser.Table_hintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.table_hint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTable_hint([NotNull] tsqlParser.Table_hintContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.index_column_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndex_column_name([NotNull] tsqlParser.Index_column_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.index_column_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndex_column_name([NotNull] tsqlParser.Index_column_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.index_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndex_value([NotNull] tsqlParser.Index_valueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.index_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndex_value([NotNull] tsqlParser.Index_valueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.column_alias_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColumn_alias_list([NotNull] tsqlParser.Column_alias_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.column_alias_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColumn_alias_list([NotNull] tsqlParser.Column_alias_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.column_alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColumn_alias([NotNull] tsqlParser.Column_aliasContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.column_alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColumn_alias([NotNull] tsqlParser.Column_aliasContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.expression_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression_list([NotNull] tsqlParser.Expression_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.expression_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression_list([NotNull] tsqlParser.Expression_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.case_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCase_expr([NotNull] tsqlParser.Case_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.case_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCase_expr([NotNull] tsqlParser.Case_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.ranking_windowed_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRanking_windowed_function([NotNull] tsqlParser.Ranking_windowed_functionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.ranking_windowed_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRanking_windowed_function([NotNull] tsqlParser.Ranking_windowed_functionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.aggregate_windowed_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAggregate_windowed_function([NotNull] tsqlParser.Aggregate_windowed_functionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.aggregate_windowed_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAggregate_windowed_function([NotNull] tsqlParser.Aggregate_windowed_functionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.all_distinct_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAll_distinct_expression([NotNull] tsqlParser.All_distinct_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.all_distinct_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAll_distinct_expression([NotNull] tsqlParser.All_distinct_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.over_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOver_clause([NotNull] tsqlParser.Over_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.over_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOver_clause([NotNull] tsqlParser.Over_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.row_or_range_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRow_or_range_clause([NotNull] tsqlParser.Row_or_range_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.row_or_range_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRow_or_range_clause([NotNull] tsqlParser.Row_or_range_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.window_frame_extent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWindow_frame_extent([NotNull] tsqlParser.Window_frame_extentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.window_frame_extent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWindow_frame_extent([NotNull] tsqlParser.Window_frame_extentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.window_frame_bound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWindow_frame_bound([NotNull] tsqlParser.Window_frame_boundContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.window_frame_bound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWindow_frame_bound([NotNull] tsqlParser.Window_frame_boundContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.window_frame_preceding"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWindow_frame_preceding([NotNull] tsqlParser.Window_frame_precedingContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.window_frame_preceding"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWindow_frame_preceding([NotNull] tsqlParser.Window_frame_precedingContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.window_frame_following"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWindow_frame_following([NotNull] tsqlParser.Window_frame_followingContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.window_frame_following"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWindow_frame_following([NotNull] tsqlParser.Window_frame_followingContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.full_table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFull_table_name([NotNull] tsqlParser.Full_table_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.full_table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFull_table_name([NotNull] tsqlParser.Full_table_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTable_name([NotNull] tsqlParser.Table_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTable_name([NotNull] tsqlParser.Table_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.view_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterView_name([NotNull] tsqlParser.View_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.view_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitView_name([NotNull] tsqlParser.View_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.func_proc_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_proc_name([NotNull] tsqlParser.Func_proc_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.func_proc_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_proc_name([NotNull] tsqlParser.Func_proc_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.ddl_object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDdl_object([NotNull] tsqlParser.Ddl_objectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.ddl_object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDdl_object([NotNull] tsqlParser.Ddl_objectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.full_column_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFull_column_name([NotNull] tsqlParser.Full_column_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.full_column_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFull_column_name([NotNull] tsqlParser.Full_column_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.column_name_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColumn_name_list([NotNull] tsqlParser.Column_name_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.column_name_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColumn_name_list([NotNull] tsqlParser.Column_name_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.column_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColumn_name([NotNull] tsqlParser.Column_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.column_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColumn_name([NotNull] tsqlParser.Column_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.cursor_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCursor_name([NotNull] tsqlParser.Cursor_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.cursor_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCursor_name([NotNull] tsqlParser.Cursor_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.on_off"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOn_off([NotNull] tsqlParser.On_offContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.on_off"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOn_off([NotNull] tsqlParser.On_offContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.clustered"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClustered([NotNull] tsqlParser.ClusteredContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.clustered"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClustered([NotNull] tsqlParser.ClusteredContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.null_notnull"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNull_notnull([NotNull] tsqlParser.Null_notnullContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.null_notnull"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNull_notnull([NotNull] tsqlParser.Null_notnullContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.scalar_function_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScalar_function_name([NotNull] tsqlParser.Scalar_function_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.scalar_function_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScalar_function_name([NotNull] tsqlParser.Scalar_function_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.data_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterData_type([NotNull] tsqlParser.Data_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.data_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitData_type([NotNull] tsqlParser.Data_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.default_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefault_value([NotNull] tsqlParser.Default_valueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.default_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefault_value([NotNull] tsqlParser.Default_valueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant([NotNull] tsqlParser.ConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant([NotNull] tsqlParser.ConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] tsqlParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] tsqlParser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.sign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSign([NotNull] tsqlParser.SignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.sign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSign([NotNull] tsqlParser.SignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterId([NotNull] tsqlParser.IdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitId([NotNull] tsqlParser.IdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.simple_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimple_id([NotNull] tsqlParser.Simple_idContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.simple_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimple_id([NotNull] tsqlParser.Simple_idContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.comparison_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparison_operator([NotNull] tsqlParser.Comparison_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.comparison_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparison_operator([NotNull] tsqlParser.Comparison_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tsqlParser.assignment_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment_operator([NotNull] tsqlParser.Assignment_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tsqlParser.assignment_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment_operator([NotNull] tsqlParser.Assignment_operatorContext context);
}
