<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>g</string>
		<string>g4</string>
	</array>
	<key>name</key>
	<string>Antlr</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>comment</key>
			<string>Double quoted strings or characters</string>
			<key>end</key>
			<string>(?&lt;=[^\\])"|(?&lt;=[^\\])\\\\"|[\\]{4}"</string>
			<key>name</key>
			<string>string.quoted.double.single-line.antlr</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>comment</key>
			<string>Single quoted strings or characters</string>
			<key>end</key>
			<string>(?&lt;=[^\\])'|(?&lt;=[^\\])\\\\'|[\\]{4}'</string>
			<key>name</key>
			<string>string.quoted.single.single-line.antlr</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?=/\*)</string>
			<key>end</key>
			<string>(?&lt;=\*/)</string>
			<key>name</key>
			<string>comment.block.antlr</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?=//)</string>
			<key>end</key>
			<string>(?&lt;=\n)</string>
			<key>name</key>
			<string>comment.block.antlr</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(grammar|returns|options|tokens|lexer grammar|import|fragment|parser grammar|locals|throws|catch|finally|mode)\b</string>
			<key>name</key>
			<string>keyword.command.antlr</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*([a-z]\w+)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.antlr</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Lexer Rules</string>
			<key>end</key>
			<string>([:])\s</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.antlr</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Dollar sign</string>
			<key>match</key>
			<string>\$</string>
			<key>name</key>
			<string>keyword.control.antlr</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*([A-Z]\w+)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.antlr</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Lexer Rules</string>
			<key>end</key>
			<string>([:])\s</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.antlr</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\=|\+\=|-\=|\*\=|/\=|//\=|%\=|&amp;\=|\|\=|\^\=|&gt;&gt;\=|&lt;&lt;\=|\*\*\=</string>
			<key>name</key>
			<string>keyword.operator.antlr</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Regex operators</string>
			<key>match</key>
			<string>[|*+?]</string>
			<key>name</key>
			<string>keyword.operator.antlr</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Section definitions like @header</string>
			<key>match</key>
			<string>^\s*(?:@)([a-z]+)\b</string>
			<key>name</key>
			<string>storage.type.function.antlr</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.antlr</string>
	<key>uuid</key>
	<string>eb5d6c6d-9170-4e02-baf3-8a62ed60b276</string>
</dict>
</plist>